name: _step.image_one

on:
  workflow_call:
    inputs:
      dockerfile_name:
        type: string
        required: true
      build_args:
        type: string
        required: true
      base_target_tags:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag_maker_script:
        type: string
        required: true
    outputs:
      imageid:
        description: Image ID
        value: ${{ jobs.image.outputs.imageid }}
      digest:
        description: Image digest
        value: ${{ jobs.image.outputs.digest }}

jobs:
  image:
    runs-on: ubuntu-latest
    outputs:
      imageid: ${{ steps.build.outputs.imageid }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - id: config
        uses: actions/github-script@v7
        with:
          script: ${{ inputs.image_tag_maker_script }}
        env:
          BASE_TARGET_TAGS: ${{ inputs.base_target_tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}
          tags: ${{ steps.config.outputs.target_tags }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: src/${{ inputs.dockerfile_name }}
          context: src
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build_args }}

      - name: Report build information
        run: |
          echo -e "### Inputs\n" >> $GITHUB_STEP_SUMMARY
          echo -e "- dockerfile_name: \`${{ inputs.dockerfile_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo -e "- build_args: \`${{ inputs.build_args }}\`" >> $GITHUB_STEP_SUMMARY
          echo -e "- base_target_tags: \`${{ inputs.base_target_tags }}\`" >> $GITHUB_STEP_SUMMARY
          echo -e "- image_name: \`${{ inputs.image_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          
          echo -e "### Image tags\n" >> $GITHUB_STEP_SUMMARY
          echo -e "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo -e "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo -e "\`\`\`" >> $GITHUB_STEP_SUMMARY
